{% set version = "3.2.1" %}

package:
  name: mistune
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mistune/mistune-{{ version }}.tar.gz
  sha256: 7c8e5501d38bac1582e067e46c8343f17d57ea1aaa735823f3aba1fd59c88a28

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing-extensions  # [py<311]

test:
  source_files:
    - tests
  requires:
    - pytest-cov
    - pip
  imports:
    - mistune
    - mistune.plugins
    - mistune.directives
  commands:
    - pip check
    # UnicodeDecodeError: 'charmap' codec can't decode byte
    - set PYTHONUTF8=1              # [win]
    - set PYTHONIOENCODING="UTF-8"  # [win]
    - pytest --cov mistune --cov-report=term-missing:skip-covered --cov-fail-under=90 --no-cov-on-fail

about:
  home: https://github.com/lepture/mistune
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A sane Markdown parser with useful plugins and renderers.
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.lepture.com

extra:
  recipe-maintainers:
    - pelson
    - bollwyvl
    - ocefpaf
