{% set version = "3.1.2" %}

package:
  name: mistune
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mistune/mistune-{{ version }}.tar.gz
  sha256: 733bf018ba007e8b5f2d3a9eb624034f6ee26c4ea769a98ec533ee111d504dff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing-extensions  # [py<311]
  run_constrained:
    # 6.1.0 pins to mistune <2 (a future version may loosen this pin)
    # see: https://github.com/conda-forge/nbconvert-feedstock/pull/54
    - nbconvert >6.1.0

test:
  source_files:
    - tests
  requires:
    - pytest-cov
    - pip
  imports:
    - mistune
    - mistune.plugins
    - mistune.directives
  commands:
    - pip check
    - pytest --cov mistune --cov-report=term-missing:skip-covered --cov-fail-under=90 --no-cov-on-fail

about:
  home: https://github.com/lepture/mistune
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A sane Markdown parser with useful plugins and renderers.
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.readthedocs.io

extra:
  recipe-maintainers:
    - pelson
    - bollwyvl
    - ocefpaf
