{% set name = "mistune" %}
{% set version = "0.7.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8517af9f5cd1857bb83f9a23da75aa516d7538c32a2c5d5c56f3789a9e4cd22f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - nose
    - python
  imports:
    - mistune
  commands:
    - nosetests

about:
  home: https://github.com/lepture/mistune
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'The fastest markdown parser in pure Python.'
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.readthedocs.io/

extra:
  recipe-maintainers:
    - pelson
    - bollwyvl
    - ocefpaf
