{% set name = "mistune" %}
{% set version = "0.8.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c0f66924ce28f03b95b210ea57e57bd0b59f479edd91c2fa4fe59331eae4a82
  patches:
    - 0001-fix-case-insensitive-refs-unit-test.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - nose
    - python
  imports:
    - mistune
  commands:
    - nosetests

about:
  home: https://github.com/lepture/mistune
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'The fastest markdown parser in pure Python.'
  description: |
    Inspired by https://github.com/chjj/marked, Mistune is the fastest markdown
    parser in pure Python with renderer features. More features include table,
    footnotes, autolink, fenced code etc.
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.readthedocs.io/
  doc_source_url: https://github.com/lepture/mistune/blob/master/README.rst

extra:
  recipe-maintainers:
    - pelson
    - bollwyvl
    - ocefpaf
