{% set name = "mistune" %}
{% set version = "3.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4c6c0c840b8637a2e9b8b6d607eb7c8f00888bf14c754409bcd339e848c2477

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing-extensions  # [py<311]

test:
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pytest-cov
    - pip
  imports:
    - mistune
    - mistune.plugins
    - mistune.directives
  commands:
    - pip check
    # UnicodeDecodeError: 'charmap' codec can't decode byte
    - set PYTHONUTF8=1              # [win]
    - set PYTHONIOENCODING="UTF-8"  # [win]
    - pytest --cov mistune --cov-report=term-missing:skip-covered --cov-fail-under=90 --no-cov-on-fail

about:
  home: https://github.com/lepture/mistune
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: A sane Markdown parser with useful plugins and renderers.
  description: A fast yet powerful Python Markdown parser with renderers and plugins.
  dev_url: https://github.com/lepture/mistune
  doc_url: https://mistune.lepture.com

extra:
  recipe-maintainers:
    - pelson
    - bollwyvl
    - ocefpaf
