# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "c1NMUVBFkF+g3calzCn2iuPgjHQfydQhGJV/13jyro3tN4KUHdsWnWg7SdKdAHV6W8M7PzYsY4in3XWzqLQUJ6TVbpZPoqTy5Z/muPsWnCsPUFDzbWJZ5IHYvAyergCbb5Xf+gJuBH7xEckTo4E0e/dGbC8DB2jRpWDwsKTB5xCzNfIl8gavbx+iKXXoNXry6AQXIVddCvMFQwzpxo90gtExW0fnXv2ENDmyU/9aQbMYHRv4LLOVnsN873qtdbBYGVqc1tRyuhni6zxUFKdn/wPGb/+qnHJY26aWgAk1TWDV8d5Dr+qrOKo8sxMYYhS4VC1sVokk9DbDWeBICoMrT6A11t7YObH/b/mtWRJ5VZzK+RmATCRYL2+oPoGfaZfH6ynICwIYvFVgdg5vT2+tPTchqf9kHhwge4Z9h9yxHrjKCDjRD4CoawX7y479d4oIVDBjBUtVEmsuyRUT3H/vZRkZPUJAEFVPvQJYSvE3akzX4jvuBe1lIpTqZmOf3pKnJiEboqCmYmym+0+cqjIZNYrBrsjXDXPHG2Si2XwLsrdW8k7ehZbT5AjWzkIpWOW8EdYdn/Svf/W9cBYfDRVcXJX471lde/BfBItQ7F6BeetXkgbQGPcYAJKD9sa85Wy2s81zYCCElbLdIuRc3nOPgWg7+ho+ZgAyqBEB01TvDCg="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
