travis:
  secure:
    BINSTAR_TOKEN: ZewlwUEg4ahQM8WvnCQyGOH68vvrMegRP9nqC/0QqFnygts87snF47CUCwC8703K4MMucPPaSoJugPRe5J9lcm/wkCuh2s9SIezyt4SUuXgvTnuoZ/aF3WQR23q8by3EdQmd2y1+/MjqaLNYk+tj5PgqjG6GIf4SrzD/bOdW1qTjqDEOei2qUjGeptCr3n32ggtgiVNCY56qgmLVIUBH6xK3aLUJiKNzxq72kgORdQpHX+kDAahwzSndfE4DSsA0PYaNIxmy5gXJek8mdNqxwr1iLZaK71o64KNSxtzTwo3jSVKoQ5vRbMxu2XbYXudx5SzdssQAsLraBfp6PqpG61yWfiQHVvN93Lma0kxmRJBQeDInaztnSyYhkiTj9S9y1xHtHi1/KhroTCBqBqY2Yizs95n3Dig3x46VqIHdUBJRHQaFUolKxmYPINzBI7fcOZhzu92+3CaOvMxbEyz382Bg3nSVbLVAOylRvlhEvNSiEQ1OlFViZLePFvgidtrV/HIZuy+FVI/ubq2kSXBwza7gYMSrzwvkK24J2ZMq9L9QkCklqBWynaUHwN1OF9gWmwuCm8yJ1hp56YDxHN9FCbHXnTZuudXZLmoE82NLDgqcfQWTVFyOlRBzzGHO8YTNet5Zko4WorhOeJ79bxwSxYE9DmTDuUd8nAJOSnT+0gk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
