travis:
  secure:
    BINSTAR_TOKEN: eEBp1Fhvo23/hU7rVlDiuZoczJwd20PkAl7fMGXZJ1x9NS9mLZ9z2b9RhNdf+Q9rccSSWnb2TRUtjnHXx/fhBWASzkwpmlTr9YYKKzTNz3OvfWpvdnTl7T1O0+SZLUs9jSgRaDfeK60u21UxxXMLLx7PU2J0kDoE7bUDDI/icNpK45/xK+FTyddsUVfSL/iDnMXBxTlrY2URgb/3GM+Im0Nlv2OORW/gDvF7JkfOlWp4IVpn+vn9bCqvdIPywG5zs2lzhu1cyYPEoMsjiUAoCiOxyVnL9+sTUEMxxKEUSZlFShzjlXObCVjBsVWycmb2vCIUZ0oWwOdHNYSodMzGI3ZdRkoqii9ujl34hju+HpjryAIZ/QRSuFTDshsXlGnT9dmhoBZx7wcFltqJ2wipjU/5tJN//TBNTLuincogS5lPDF0inK9UVWvi6TX3kYavMbe0KzLd9PiC1zXFuk57taLPiPGuHhjASj16v697Elnczwpiiyo8eOrmyOGQJmtrLamahDa6Hm3rr9rl/VrgxK3YN9jLFzsBw8fBbR6e2d2x8RZY8ITQqTC2BKKPaFwSHjmQJGa4W7Ww6nQ8EIsuAppNQxOEJizwxvUmjbHneDbKJuLV5iyhBqlo2J0UaHukNo6U/0ZdAMPkWHwi25+StVSaL4r0U8DcUGWSGUnCeWA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
